config/routes.rb
AristoLms::Engine.routes.draw do


  get '/start/:training_id', to: 'trainings#start_module', as: 'start_training'

  post '/answer', to: 'subscriptions#quiz', as:'submit_answer'

  get '/finish', to: 'subscriptions#finish', as: 'finish_track'

  resources :subscriptions do
    member do
      get :start
    end
  end


  scope ':root_node' do
    resources :trainings do
      collection do
        patch :sort
      end

      collection do
        patch :sort_children
      end
    end
  end

# root 'subscriptions#index' 


end

app/models/aristo_lms/answer.rb
module AristoLms
  class Answer < ApplicationRecord
    validates_presence_of [:user_id, :attempt_id]
  end
end

app/models/aristo_lms/application_record.rb
module AristoLms
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/aristo_lms/attempt.rb
module AristoLms
  class Attempt < ApplicationRecord
    belongs_to :subscription
    has_many :answers
    has_many :switches

    validates_presence_of [:user_id, :subscription_id, :current_node_id]
  end
end

app/models/aristo_lms/mark.rb
module AristoLms
  class Mark < ApplicationRecord
    validates_presence_of [:training_id, :user_id]
  end
end

app/models/aristo_lms/status.rb
module AristoLms
  class Status < ApplicationRecord
  end
end

app/models/aristo_lms/subscription.rb
module AristoLms
  class Subscription < ApplicationRecord
    belongs_to :training
    belongs_to :user, class_name: AristoLms.user_class
    has_many :statuses
    has_many :attempts
    validates_presence_of [:training_id, :user_id]
  end
end

app/models/aristo_lms/switch.rb
module AristoLms
  class Switch < ApplicationRecord
    belongs_to :attempt
  end
end

app/controllers/aristo_lms/application_controller.rb
module AristoLms
  class ApplicationController < ::ApplicationController
    layout AristoLms.layout || 'application'
    protect_from_forgery with: :exception
  end
end

app/controllers/aristo_lms/contents_controller.rb
require_dependency "aristo_lms/application_controller"

module AristoLms
  class ContentsController < ApplicationController
    before_action :get_training
    before_action :set_content, only: [:show, :edit, :update, :destroy]

    # GET /contents
    def index
      @contents = @training.contents
    end

    # GET /contents/1
    def show
    end

    # GET /contents/new
    def new
      @content = @training.contents.build
    end

    # GET /contents/1/edit
    def edit
    end

    # POST /contents
    def create
      @content = @training.contents.build(content_params)

      if @content.save
        redirect_to training_content_path(@content), notice: 'Content was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /contents/1
    def update
      if @content.update(content_params)
        redirect_to training_content_path(@content), notice: 'Content was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /contents/1
    def destroy
      @content.destroy
      redirect_to training_posts_path, notice: 'Content was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def get_training
        @training = Training.find(params[:training_id])
      end

      def set_content
        @content = @training.contents.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def content_params
        params.require(:content).permit(:name, :content)
      end
  end
end

app/controllers/aristo_lms/options_controller.rb
require_dependency "aristo_lms/application_controller"

module AristoLms
  class OptionsController < ApplicationController
    before_action :set_option, only: [:show, :edit, :update, :destroy]
    before_action :get_training
    before_action :get_question

    # GET /options
    def index
      @options = Option.all
    end

    # GET /options/1
    def show
    end

    # GET /options/new
    def new
      @option = @question.options.build
    end

    # GET /options/1/edit
    def edit
    end

    # POST /options
    def create
      @option = Option.new(option_params)

      if @option.save
        redirect_to training_path(@training), notice: 'Option was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /options/1
    def update
      if @option.update(option_params)
        redirect_to training_path(@training), notice: 'Option was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /options/1
    def destroy
      @option.destroy
      redirect_to training_path(@training), notice: 'Option was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_option
        @option = Option.find(params[:id])
      end

      def get_question
        @question = Question.find(params[:question_id])
      end

      def get_training
        @training = Training.find(params[:training_id])
      end

      # Only allow a trusted parameter "white list" through.
      def option_params
        params.require(:option).permit(:option_text, :question_id)
      end
  end
end

app/controllers/aristo_lms/questions_controller.rb
require_dependency "aristo_lms/application_controller"

module AristoLms
  class QuestionsController < ApplicationController
    before_action :get_training
    before_action :set_question, only: [:show, :edit, :update, :destroy]

    # GET /questions
    def index
      @questions = @training.questions
    end

    # GET /questions/1
    def show
    end

    # GET /questions/new
    def new
      @question = @training.questions.build
      3.times do
        option = @question.options.build
      end
    end

    # GET /questions/1/edit
    def edit
    end

    # POST /questions
    def create
      @question = @training.questions.build(question_params)

      if @question.save
        redirect_to training_path(@training), notice: 'Question was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /questions/1
    def update
      if @question.update(question_params)
        redirect_to training_question_path(@training), notice: 'Question was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /questions/1
    def destroy
      @question.destroy
      redirect_to training_questions_path(@training), notice: 'Question was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_question
        @question = @training.questions.find(params[:id])
      end

      def get_training
        @training = Training.find(params[:training_id])
      end

      # Only allow a trusted parameter "white list" through.
      def question_params
        params.require(:question).permit(:question_text, options_attributes: [:option_text, :is_correct])
      end
  end
end

app/controllers/aristo_lms/subscriptions_controller.rb
# require_dependency "aristo_lms/application_controller"

module AristoLms
  class SubscriptionsController < ApplicationController
    before_action :set_current_user, only: [:index, :new]
    before_action :set_subscription, only: [:show, :start]

    def index
      @subscriptions = Subscription.where(user_id: current_user.id)
    end

    def new
      @trainings = Training.where(parent_id: nil)
    end


    def create
      @subscription = Subscription.create(training_id: params[:training_id], user_id: current_user.id )
      if @subscription.save
        redirect_to helpers.switch_subscriptions
      else
        redirect_to new_subscription_path, alert: "Not added"
      end
    end


    def finish
      @attempt = Attempt.where(subscription_id: params[:subscription_id], user_id: current_user.id).order(:created_at).last
      if @attempt.total_question == 0
        @attempt.result = "pass"
      elsif @attempt.total_question !=0 && @attempt.score == 0
        @attempt.result = "fail"
      elsif @attempt.score != 0 && @attempt.score / @attempt.total_question * 100 >= 50
        @attempt.result = "pass"
      else
        @attempt.result = "fail"
      end
      @attempt.update(completed: true)
      redirect_to helpers.switch_subscriptions
    end

    def quiz
      # render plain: params.inspect

      if !(params[:answer][:multiple_answer_ids].nil?)
        @answer = Answer.new(user_id: current_user.id, question_id: params[:answer][:question_id],
                    multiple_answer_ids: params[:answer][:multiple_answer_ids].join(","), attempt_id: params[:answer][:attempt_id])
      else
        @answer = Answer.new(user_id: current_user.id, question_id: params[:answer][:question_id],
          answer_id: params[:answer][:answer_id], attempt_id: params[:answer][:attempt_id])
      end

      @answer.save

      @siblings_after = Training.find(params[:answer][:question_id]).siblings_after
      @subscription = Subscription.find(params[:answer][:subscription_id])
      @active_module = Training.find(params[:answer][:module_id])


      @question = Training.find(params[:answer][:question_id])
      if @question.children.where(correct: "yes").length == 1
        if @question.children.where(correct: "yes").first.id  == params[:answer][:answer_id].to_i
          @attempt = Attempt.where(subscription_id: params[:answer][:subscription_id], user_id: current_user.id).order(:created_at).last

          @attempt.increment!(:score)
        end
      else
        @right_answer_ids = @question.children.where(correct: "yes").map{|object| object.id.to_s }
        puts(@right_answer_ids)
        if !(@right_answer_ids.difference(params[:answer][:multiple_answer_ids]).any?)
          @attempt = Attempt.where(subscription_id: params[:answer][:subscription_id], user_id: current_user.id).last

          @attempt.increment!(:score)
        end
      end



      if @siblings_after.length != 0
        @active_node = @siblings_after.first
        redirect_to subscription_path(@subscription, active_module_id: @active_module, immediate_parent: @active_node.parent, active_node_id: @active_node)
      else
        @active_node = Training.find(params[:answer][:question_id])
        redirect_to finish_track_path(subscription_id: @subscription)
      end
    end

    def start
      @active_node = @subscription.training.children.first
      @attempt = Attempt.new(user_id: current_user.id, subscription_id: @subscription.id, current_node_id: @active_node.id,
                              total_question: 0)
      @attempt.save
      redirect_to subscription_path(@subscription, active_node_id: @active_node.id)
    end

    def show
      @active_module_id = params[:active_module_id]
      @active_node_id  = params[:active_node_id]
      @immediate_parent_id = params[:immediate_parent_id]

      @attempt = Attempt.where(user_id: current_user.id, subscription_id: @subscription.id).order(:created_at).last

      # @active_node = @subscription.training.children.first
      # @attempt = Attempt.new(user_id: current_user.id, subscription_id: @subscription.id, current_node_id: @active_node.id,
      #                         total_question: 0)
      # @attempt.save

      if params[:active_node_id].nil?
        @active_node  = @subscription.training
        @immediate_parent = @subscription.training
      else
        @active_node  = Training.find(params[:active_node_id])
        @active_module = @active_node.ancestors[@active_node.ancestors.length - 2]
        @immediate_parent = @active_node.parent
        @attempt.update(current_node_id: @active_node.id)
      end

      if @active_node.category == "module"
        @finished = params[:finished_module] ? params[:finished_module] : false
      end

      if @active_node.category == "switch" && !(params[:finished_module_id].nil?)
        @training_id = Training.find(params[:finished_module_id]).id
        @switch = Switch.new(attempt_id: @@attempt.id, training_id: params[:finished_module_id], completed: true)
        @switch.save
      end


      if @active_node.category == "question"
        @attempt.increment!(:total_question)
        @answer = Answer.new
        if @active_node.children.where(correct: "yes").length > 1
          @mcq = true
        end
      end


    end

    private

    def subscription_params
      params.require(:subscription).permit(:training_id, :user_id)
    end

    def answer_params
      params.require(:answer).permit(:attempt_id, :question_id, :answer_id, :subscription_id, :module_id)
    end

    def attempt_params
      params.require(:attempt).permit(:user_id, :subscription_id, :current_node_id, :total_question, :score,
                                      :completed, :result)
    end

    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def set_current_user
      if !current_user
        redirect_to main_app.root_path, alert: "Please Sign in to view your subscriptions"
      end
    end
  end
end

app/controllers/aristo_lms/trainings_controller.rb
require_dependency "aristo_lms/application_controller"

module AristoLms
  class TrainingsController < ApplicationController

    before_action :set_training, only: [:show, :edit, :update, :destroy]
    before_action :user_existing
    before_action :set_root_node


    # GET /trainings
    def index
      @trainings = @root_node.children #Training.where(parent_id: nil).order(sort_order: :asc)
    end

    def sort
      params[:training].each_with_index do |id, index|
        Training.where(id: id).update_all(sort_order: index)
      end
      head :ok
    end

    def sort_children
      params[:training].each_with_index do |id, index|
        Training.where(id: id).update_all(sort_order: index)
      end
    end

    # GET /trainings/1
    def show
      @current_user = current_user
      @is_arisro_admin = is_aristo_admin
      @modules = @training.children
    end

    def start_module
      @training = Training.find(params[:training_id])
      @status = Status.new(user_id: current_user.id, training_id: @training.id, immediate_parent_id: @training.parent.id || @training.parent ,
        root_id: @training.ancestors.last.id || @training.ancestors.last )
      if @status.save
        redirect_to training_path(@training, root_node: params[:root_node])
      else
        redirect_to switch_subscriptions
      end
    end

    # GET /trainings/new
    def new
      @parent_id = params[:parent_id]
      @category = params[:category]

      if @category == "question"
        @label = "question"
        @detail = "More details if any"
      end

      if @category == "option"
        @label = "option"
        @detail = "More information on why it is wright or wrong"
      end

      @training = Training.new
      @training.parent_id = params[:parent_id]
      @training.category = params[:category]
    end

    # GET /trainings/1/edit
    def edit
    end

    # POST /trainings
    def create
      @training = Training.new(training_params)
      @training.user_id = current_user.id
      if @training.save
        redirect_to training_path(@training, root_node: params[:root_node]), notice: 'Training was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /trainings/1
    def update
      if @training.update(training_params)
        redirect_to training_path(@training, root_node: params[:root_node]), notice: 'Training was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /trainings/1
    def destroy
      @training.destroy
      redirect_to trainings_url(root_node: params[:root_node]), notice: 'Training was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_training
        @training = Training.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def training_params
        params.require(:training).permit(:name, :description, :parent_id, :category, :content, :correct, :cover_image)
      end

      def set_root_node
        # @root_node = Training.find_or_create_by_path([{name: params[:root_node], category: 'root'}])
        @root_node = Training.roots.where(name: params[:root_node]).first_or_create(user: current_user, category: "root")
        # @root_node.save
      end

      def user_existing
        if !(is_aristo_admin)
          redirect_to switch_subscriptions, alert: "You are not allowed to do that"
        end
      end

  end
end

app/helpers/aristo_lms/application_helper.rb
require "webpacker/helper"

module AristoLms
  module ApplicationHelper
    include ::Webpacker::Helper

    def current_webpacker_instance
      AristoLms.webpacker
    end

    def method_missing method, *args, &block
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    def switch_subscriptions
      if AristoLms.redirect_to_root
        main_app.root_path
      else
        subscriptions_path
      end
    end

  end
end

app/helpers/aristo_lms/contents_helper.rb
module AristoLms
  module ContentsHelper
  end
end

app/helpers/aristo_lms/option_helper.rb
module AristoLms
  module OptionHelper
  end
end

app/helpers/aristo_lms/options_helper.rb
module AristoLms
  module OptionsHelper
  end
end

app/helpers/aristo_lms/questions_helper.rb
module AristoLms
  module QuestionsHelper
  end
end

app/helpers/aristo_lms/subscription_helper.rb
module AristoLms
  module SubscriptionHelper
  end
end

app/views/aristo_lms/trainings/_form.html.slim
= form_with(model: training, url: training.new_record? ? trainings_path(root_node: params[:root_node]) : training_path(training, root_node: params[:root_node]), local: true) do |form|
  - if training.errors.any?
    #error_explanation
      h2
        = pluralize(training.errors.count, "error")
        | prohibited this training from being saved:
      ul
        - training.errors.full_messages.each do |message|
          li= message
  .form-group
    = form.label @label || :name
    = form.text_field :name, class: "form-control", required: true
    = form.hidden_field :parent_id
    = form.hidden_field :category
  - if form.object.category=="option"
    .form-group
      = form.label :correct
      = form.select :correct, ['yes', 'no'], {}, class: 'form-control'
  - if form.object.category == "training" or form.object.category == "module"  or form.object.category == "track" 
    .form-group
      = form.label @detail || :description
      = form.text_area :description, class: "form-control"
    .form-group
      = form.label :cover_image
      = form.file_field :cover_image
  - else
    .form-group
      = form.label :content
      = form.rich_text_area :content
  .actions
    = form.submit "Save", class: "btn btn-outline-primary"

app/views/aristo_lms/trainings/edit.html.slim
h1 Edit #{@training.category.titleize}
= render 'form', training: @training
br/
= link_to 'Show', training_path(@training, root_node: params[:root_node])
| \
= link_to 'Back', trainings_path(root_node: params[:root_node])

app/views/aristo_lms/trainings/index.html.slim
p#notice= notice
h1 Tracks
/! listing tracks
  /! link for new training
/ .row
  .col-sm-4.col-md-4
    = link_to new_training_path(category: "track", root_node: params[:root_node]), class: "hover-link" do
      .card.h-100.border.border-primary.new-content-add-card
        .card-body
          center
            = image_tag("aristo_lms/plus.png", style: "width:100%")
            h3 Add new track
  / .col-sm-4.col-md-4
    = link_to new_training_path(category: "training", root_node: params[:root_node]), class: "hover-link" do
      .card.h-100.border.border-primary.new-content-add-card
        .card-body
          center
            = image_tag("aristo_lms/plus.png", style: "width:100%")
            h3 Add new track
/ #tracks.row data-url=sort_trainings_path
  - @trainings.each do |training|
    .col-sm-4.col-md-4 id="#{dom_id(training)}"
      .card.h-100.border.border-primary
        .card-body
          h3.card-title.training-title= training.name
          p.card-text= training.description
        .card-body.d-flex.flex-column
          = link_to 'Show', training, class: "btn btn-outline-primary mt-auto"
          = link_to 'Edit', edit_training_path(training, root_node: params[:root_node]), class: "btn btn-outline-primary mt-auto"
          = link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger mt-auto"

= link_to 'Create Track', new_training_path(parent_id: @root_node.id, category: "track", root_node: params[:root_node]), class: "btn btn-outline-primary"
/ = link_to 'Create Track', new_training_path(parent_id: @root_node, category: "track", root_node: params[:root_node]), class: "btn btn-outline-primary"
br/
#training-children.list-group data-url=sort_trainings_path
  - @trainings.each do |node|
    .list-group-item id="#{dom_id(node)}"
      .row
        .col-sm-6.col-md-6
          h4.training-title= node.name
        .col-sm-6.col-md-6
          = link_to "Show", training_path(node, root_node: params[:root_node]), class: "btn btn-outline-primary"
          | |
          = link_to "Edit", edit_training_path(node, root_node: params[:root_node]), class: "btn btn-outline-primary"
          | |
          = link_to 'Destroy', training_path(node, root_node: params[:root_node]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger mt-auto"

app/views/aristo_lms/trainings/new.html.slim
- if @parent.nil?
  h1 New #{@training.category.titleize}
- else
  h1
    | New Module under #{@parent.name}
= render 'form', training: @training
br/
- if @parent && (@parent.ancestors != [] || @parent.parent)
  = link_to 'Back', training_path(@parent.ancestors.last || @parent.parent, root_node: params[:root_node])
- elsif @parent
  = link_to 'Back', training_path(@parent, root_node: params[:root_node])
- else
  = link_to 'Back', trainings_path(root_node: params[:root_node])

app/views/aristo_lms/trainings/show.html.slim
p#notice= notice
/! start of name and description
.row
  .col-sm-6.col-md-6
    h1.training-title= @training.name
  .col-sm-6.col-md-6
    - if @is_arisro_admin
      = link_to 'Edit', edit_training_path(@training, root_node: params[:root_node]), class: "btn btn-outline-primary"
      | |
    - if @training.parent and @training.parent.category != "root" 
      = link_to 'Back', training_path(@training.parent, root_node: params[:root_node]), class: "btn btn-outline-primary"
    / - elsif @current_user && !@is_arisro_admin
      = link_to 'Back', switch_subscriptions, class: "btn btn-outline-primary"
    / - if @training.parent && @training.ancestors.length == 2
    /   = link_to 'Back', training_path(@training.ancestors.last, root_node: params[:root_node]), class: "btn btn-outline-primary"
    / - elsif @training.parent
    /   = link_to 'Back', training_path(@training.parent, root_node: params[:root_node]), class: "btn btn-outline-primary"
    / - elsif @current_user && !@is_arisro_admin
    /   = link_to 'Back', switch_subscriptions, class: "btn btn-outline-primary"
    - else
      = link_to 'Back', trainings_path(root_node: params[:root_node]), class: "btn btn-outline-primary"
== render "aristo_lms/trainings/content_type/#{@training.category}"

/ - if @training.category == "question_answer_session"
  h3.training-title Listing Questions
  br/
  - @training.children.each do |mod|
    .row
      .col-md-6
        h3= mod.name
      .col-md-6
        = link_to "Add Option", new_training_path(parent_id: mod.id, category: "option", root_node: params[:root_node]), class: "btn btn-outline-primary"
        = link_to 'Destroy', mod, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger mt-auto"
    p= mod.description
    - mod.children.order(:position).each do |option|
      h5= option.name